# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-11-25 15:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='remarks',
            field=models.CharField(default='1', help_text='Remarks of the task', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='task_status',
            field=models.CharField(choices=[('1', 'Not submitted'), ('2', 'under process'), ('3', 'completed')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='submitted',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 25, 20, 31, 20, 573911)),
        ),
    ]
