# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-11-26 05:14
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taskapp', '0002_auto_20181125_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='username',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='submitted',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 26, 10, 44, 26, 255097)),
        ),
    ]
