# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-11-26 06:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0003_auto_20181126_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='last_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 26, 12, 29, 29, 64879)),
        ),
        migrations.AlterField(
            model_name='task',
            name='submitted',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 26, 12, 29, 29, 64789)),
        ),
    ]
