# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-11-26 16:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0005_auto_20181126_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='last_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 26, 22, 21, 7, 958776)),
        ),
        migrations.AlterField(
            model_name='task',
            name='submitted',
            field=models.DateTimeField(default=''),
        ),
    ]
