# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-11-26 16:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0006_auto_20181126_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='last_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 26, 22, 23, 19, 97160)),
        ),
        migrations.AlterField(
            model_name='task',
            name='submitted',
            field=models.DateTimeField(blank=True, default='null', null=True),
        ),
    ]
